### ISSUE TITLE
ValueError: please add max length column for VarLenSparseFeat of DIN/DIEN input

### ISSUE THREAD

**Issue by Gavince** [shenweichen/DeepCTR-Torch#146]
当我运行DIN torch版本时出现了以下错误, 但是我在TF版本上可以正常运行,数据未变:

编码:varlen_feature_columns = [VarLenSparseFeat(SparseFeat(name=feat, vocabulary_size=35380+1
                                                          , embedding_dim=emb_dim, embedding_name="click_article_id"), maxlen=max_len) for feat in hist_behavior_fea]

错误:ValueError: please add max length column for VarLenSparseFeat of DIN/DIEN input

**Comment by zanshuxun** [comment]
请使用Bug report模板：
**Describe the bug(问题描述)**
A clear and concise description of what the bug is.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.6]
 - torch version [e.g. 1.6.0, 1.7.0]
 - deepctr-torch version [e.g. 0.2.4,]

**Additional context**
Add any other context about the problem here.
