### ISSUE TITLE
ValueError: could not convert string to float: '5a9ed9b0'

### ISSUE THREAD

**Issue by mjrzzz** [shenweichen/DeepCTR-Torch#202]
ValueError: could not convert string to float: '5a9ed9b0'

fit_transform出现这个错误

**Comment by zanshuxun** [comment]
请按照Bug report模板给出更多信息：

**Describe the bug(问题描述)**
A clear and concise description of what the bug is.

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.6]
 - torch version [e.g. 1.6.0, 1.7.0]
 - deepctr-torch version [e.g. 0.2.7,]

**Additional context**
Add any other context about the problem here.
