### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by LSC527** [shenweichen/DeepCTR-Torch#88]
**Describe the bug(问题描述)**
照着example跑deepfm的时候，model.fit的时候报错  
![TIM截图20200519172818](https://user-images.githubusercontent.com/34333110/82309831-35182200-99f6-11ea-9ecd-24a38555272c.png)  

**Operating environment(运行环境):**
 - python version 3.7.6
 - torch version 1.5.0+cu101
 - deepctr-torch version 0.2.1

**Comment by DelaiahZ** [comment]
I have the same problem，Have you found a solution？

**Comment by DelaiahZ** [comment]
total_loss.backward(retain_graph=True)   ---》 loss.backward(retain_graph=True)      
solve the problem

**Comment by chengrufeng** [comment]
same problem + 1

**Comment by ZhangYuef** [comment]
Same as #90  . The problem is caused by `self.reg_loss` part.  It's a known bug now and wait for elegant fixing. We can refer to #91 's method to move the whole computation process of regularization into network forward part.

Also, if we don't use `DIEN` model at this moment we can get rid of `self.aux_loss`.

**Comment by shenweichen** [comment]
we have solved this issue in new version , please use `pip install -U deepctr-torch` to upgrade.
